

# Chapter4 wrap-up

    - 신경망 학습의 지표는 손실함수(Loss Function)
    - 손실함수에는 MSE(주로 회귀문제에 사용)와 CEE(주로 분류문제에 사용)를 사용한다
    - 손실함수의 값이 작아지는 방향으로 가중치 매개변수를 갱신
    - 가중치 매개변수를 갱신할 때는 가중치 매개변수의 기울기를 이용, 기울어진 방향으로 가중치값을 반복해서 갱신
    - 수치 미분을 이용해서 가중치 매개변수의 기울기를 구할 수 있다
    - 수치 미분을 이용한 기울기 계산법은 단순하고 구현하기도 쉽지만(?!) 시간이 오래 걸린다
    - 오차역전파법을 통하면 빠르게 구할 수 있다


# 5 오차역전파법

    - 수식을 통해 이해하는 방법과 계산 그래프를 통해 이해하는 방법
    - 이 책에서는 계산 그래프를 통해 시각적으로 쉽게 설명


## 5.1 계산그래프

      - 노드와 에지로 표현되는 그래프 자료구조로 표현
        
### 5.1.1 계산 그래프로 풀다

        가. 문제 1 : 1개에 100원인 사과를 2개 샀다. 소비세가 10%일 때 지불금액 구하기
          - 계산그래프로 풀기
          - 사과의 갯수와 소비세를 변수로 취급해서 표기
        
        나. 문제 2 : 100원짜리 사과 2개, 150원짜리 귤 3개, 소비세 10%일 때 지불금액 구하기
          - 문제 1과 동일한 방식으로 계산그래프로 표기해서 풀기
        
        다.그래프 상 계산은 왼쪽에서 오른쪽으로 진행 (순전파 : forward propagation)

### 5.1.2 국소적 계산
        
        가. 사과 2개 포함한 여러 식품을 구입하는 case
          - 사과 제외한 여러 식품의 총 금액은 4,000원
          - 사과와 여러 식품의 값을 더하는 계산은 두 가지 숫자만 계산하면 끝
          - 각 노드는 자신과 관련된 계산 이외에는 신경쓰지 않아도 됨
          - 단계별로 <국소적 계산>을 수행해서 단순한 방식으로 전체 복잡한 계산 가능
          
### 5.1.3 왜 계산 그래프로 푸는가?

        가. 국소적 계산으로 단순하게 풀기 위해
        나. 역전파를 통해 <미분>을 효율적으로 계산할 수 있어서
        다. 문제 1 case : 사과가격이 오르면 최종 금액에 어떤 영향을 끼치는가?
          - 사과 가격에 대한 지불 금액의 미분값을 구하는 문제 (dL / dx)
          - 사과 가격이 1 오르면 최종 금액은 2.2배만큼 오른다


## 5.2 연쇄법칙

      - 역전파는 국소적인 미분을 연쇄법칙에 의해 오른쪽에서 왼쪽으로 전달

### 5.2.1 계산 그래프의 역전파

        가. case : y = f(x) 함수의 역전파
          - 신호 E(상류에서 전달된 값)에 노드의 국소적 미분 (dy/dx)을 곱해서 다음 노드로 전달

### 5.2.2 연쇄법칙이란?

        가. 합성함수 : 여러 함수로 구성된 함수
          - z = (x + y)**2 식은
            z = t**2 와 t = x + y 라는 두 개의 식으로 구성
        나. 연쇄법칙 : 합성함수의 미분에 대한 성질
          - 합성함수의 미분은 합성함수를 구성하는 각 함수의 미분의 곱
          - dz/dx = dz/dt * dt/dx
          - dz/dt = 2t
            dt/dx = 1
            dz/dx = dz/dt * dt/dx = 2t * 1 = 2(x + y)
            
### 5.2.3 연쇄법칙과 계산 그래프

        가. 역전파가 하는 일은 <연쇄법칙>의 원리와 동일
        
        
## 5.3 역전파

### 5.3.1 덧셈 노드의 역전파

        가. case : z = x + y
          - dz/dx = 1, dz/dy = 1
        나. 덧셈 노드의 역전파는 1을 곱하기만 할 뿐 상류에서 입력된 값을 그대로 다음 노드로 전달

### 5.3.2 곱셈 노드의 역전파

        가. case : z = xy
          - dz/dx = y, dz/dy = x
        나. 곱셈 노드의 역전파는 상류에서 입력된 값에 순전파 때의 입력 신호들을 서로 바꿔서 다음 노드로 전달
        다. 덧셈 역전파는 순방향 입력 신호값이 필요없고, 곱셈은 순전파의 입력 신호를 변수에 저장
        
### 5.3.3 사과 쇼핑의 예

        가. 사과 쇼핑 case (문제 1)
          - 세 변수가 최종 금액에 어떻게 영향을 주는가 (사과 가격, 사과 갯수, 소비세)
        나. 사과 & 귤 쇼핑 case (문제 2)



## 5.4 단순한 계층 구현하기

In [3]:
# 5.4.1 곱셈 계층

class MulLayer:
    def __init__(self):
        self.x = None
        self.y = None
        
    def forward(self, x, y):
        self.x = x
        self.y = y
        out = x * y
        
        return out
    
    def backward(self, dout):
        dx = dout * self.y  # x와 y를 바꾼다
        dy = dout * self.x
        
        return dx, dy

In [4]:
# 문제 1 : 사과 case

apple = 100
apple_num = 2
tax = 1.1

# 계층들
mul_apple_layer = MulLayer()
mul_tax_layer = MulLayer()

# 순전파
apple_price = mul_apple_layer.forward(apple, apple_num)
price = mul_tax_layer.forward(apple_price, tax)

print(price)  # 220

220.00000000000003


In [5]:
# 역전파
dprice = 1
dapple_price, dtax = mul_tax_layer.backward(dprice)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)

print(dapple, dapple_num, dtax)  # 2.2 110 200

2.2 110.00000000000001 200


In [6]:
# 5.4.2 덧셈 계층

class AddLayer:
    def __init__(self):
        pass
    
    def forward(self, x, y):
        out = x + y
        return out
    
    def backward(self, dout):
        dx = dout * 1
        dy = dout * 1
        return dx, dy

In [7]:
# 문제 2 : 사과 & 오렌지 case

apple = 100
apple_num = 2
orange = 150
orange_num = 3
tax = 1.1

# 계층들
mul_apple_layer = MulLayer()
mul_orange_layer = MulLayer()
add_apple_orange_layer = AddLayer()
mul_tax_layer = MulLayer()

# 순전파
apple_price = mul_apple_layer.forward(apple, apple_num)  #(1)
orange_price = mul_orange_layer.forward(orange, orange_num)  #(2)
all_price = add_apple_orange_layer.forward(apple_price, orange_price)  #(3)
price = mul_tax_layer.forward(all_price, tax)  #(4)

# 역전파
dprice = 1
dall_price, dtax = mul_tax_layer.backward(dprice)  #(4)
dapple_price, dorange_price = add_apple_orange_layer.backward(dall_price)  #(3)
dorange, dorange_num = mul_orange_layer.backward(dorange_price)  #(2)
dapple, dapple_num = mul_apple_layer.backward(dapple_price)  #(1)

print(price)  # 715
print(dapple_num, dapple, dorange, dorange_num, dtax)  # 110 2.2 3.3 165 650

715.0000000000001
110.00000000000001 2.2 3.3000000000000003 165.0 650


## 5.5 활성화 함수 계층 구현하기

In [8]:
# 5.5.1 Relu 계층

class Relu:
    def __init__(self):
        self.mask = None
        
    def forward(self, x):
        self.mask = (x <= 0)
        out = x.copy()
        out[self.mask] = 0
        
        return out
    
    def backward(self, dout):
        dout[self.mask] = 0
        dx = dout
        
        return dx

In [10]:
import numpy as np
x = np.array( [[1.0, -0.5], [-2.0, 3.0]] )
print(x)

[[ 1.  -0.5]
 [-2.   3. ]]


In [11]:
mask = (x <= 0)
print(mask)

[[False  True]
 [ True False]]


In [12]:
# 5.5.2 Sigmoid 계층

class Sigmoid:
    def __init__(self):
        self.out = None
        
    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out
        
        return out
    
    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        
        return dx

## 5.6 Affine/Softmax 계층 구현하기

In [14]:
# 5.6.1 Affine 계층

X = np.random.rand(2)    # 입력
W = np.random.rand(2,3)  # 가중치
B = np.random.rand(3)    # 편향

X.shape  # (2,)
W.shape  # (2, 3)
B.shape  # (3,)

Y = np.dot(X, W) + B

print(X.shape)
print(W.shape)
print(B.shape)
print(Y)

(2,)
(2, 3)
(3,)
[0.42187601 0.74008068 0.93810834]


In [15]:
# 5.6.2 배치용 Affine 계층

X_dot_W = np.array([[0,0,0], [10, 10, 10]])
B = np.array([1, 2, 3])

X_dot_W

array([[ 0,  0,  0],
       [10, 10, 10]])

In [16]:
X_dot_W + B

array([[ 1,  2,  3],
       [11, 12, 13]])

In [17]:
dY = np.array([[1, 2, 3], [4, 5, 6]])
dY

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
dB = np.sum(dY, axis=0)
dB

array([5, 7, 9])

In [20]:
class Affine:
    def __init__(self, W, b):
        self.W = W
        self.b = b
        self.x = None
        self.dW = None
        self.db = None
        
    def forward(self, x):
        self.x = x
        out = np.dot(x, self.W) + self.b
        
        return out
    
    def backward(self, dout):
        dx = np.dot(dout, self.W.T)
        self.dW = np.dot(self.x.T, dout)
        self.db = np.sum(dout, axis=0)
        
        return dx

In [21]:
# 5.6.3 Softmax-with-Loss 계층

class SoftmaxWithLoss:
    def __init__(self):
        self.loss = None  # 손실
        self.y = None     # Softmax의 출력
        self.t = None     # 정답 레이블(one-hot 벡터)
        
    def forward(self, x, t):
        self.t = t
        self.y = softmax(x)
        self.loss = cross_entropy_error(self.y, self.t)
        
        return self.loss
    
    def backward(self, dout=1):
        batch_size = self.t.shape[0]
        dx = (self.y - self.t) / batch_size
        
        return dx

## 5.7 오차역전파법 구현하기


### 5.7.1 신경망 학습의 전체 그림

        가. 전제
          - 신경망에는 적응 가능한 가중치와 편향이 있고
          - 가중치와 편향을 훈련 데이터에 적응하도록 조정하는 과정을 <학습>이라 한다
          - 신경망 학습은 다음의 4단계로 수행
        
        나. 1단계 : 미니배치
          - 훈련 데이터 중 일부를 random으로 발췌(미니배치), 미니배치의 손실 함수 값 최소화가 목표
        
        다. 2단계 : 기울기 산출
          - 미니배치의 손실 함수 값을 줄이기 위해 각 가중치 매개변수 기울기 산출
          - 기울기는 손실 함수 값을 가장 작게 하는 방향을 제시
          
        라. 3단계 : 매개변수 갱신
          - 가중치 매개변수를 기울기 방향으로 아주 조금씩 갱신
          
        마. 4단계 : 반복
          - 1~3단계 반복


In [31]:
# 5.7.2 오차역전파법을 적용한 신경망 구현하기

import sys, os
sys.path.append(os.pardir)
import numpy as np

from src.common.layers import *
from src.common.gradient import numerical_gradient
from collections import OrderedDict


class TwoLayerNet:
    
    def __init__(self, input_size, hidden_size, output_size,
                 weight_init_std=0.01):
        
        # 가중치 초기화
        self.params = {}
        self.params['W1'] = weight_init_std * \
                            np.random.randn(input_size, hidden_size)
        self.params['b1'] = np.zeros(hidden_size)
        self.params['W2'] = weight_init_std * \
                            np.random.randn(hidden_size, output_size)
        self.params['b2'] = np.zeros(output_size)
        
        # 계층 생성
        self.layers = OrderedDict()
        self.layers['Affine1'] = Affine(self.params['W1'], self.params['b1'])
        self.layers['Relu1'] = Relu()
        self.layers['Affine2'] = Affine(self.params['W2'], self.params['b2'])
        
        self.lastLayer = SoftmaxWithLoss()
        
    def predict(self, x):
        for layer in self.layers.values():
            x = layer.forward(x)
            
            return x
        
    # x : 입력데이터, t : 정답 레이블
    def loss(self, x, t):
        y = self.predict(x)
        return self.lastLayer.forward(y, t)
    
    def accuracy(self, x, t):
        y = self.predict(x)
        y = np.argmax(y, axis=1)
        if t.ndim != 1 : t = np.argmax(t, axis=1)
        
        accuracy = np.sum(y == t) / float(x.shape[0])
        return accuracy
    
    # x : 입력 데이터, t : 정답 레이블
    def numerical_gradient(self, x, t):
        loss_W = lambda W: self.loss(x, t)
        
        grads = ()
        grads['W1'] = numerical_gradient(loss_W, self.params['W1'])
        grads['b1'] = numerical_gradient(loss_W, self.params['b1'])
        grads['W2'] = numerical_gradient(loss_W, self.params['W2'])
        grads['b2'] = numerical_gradient(loss_W, self.params['b2'])
        return grads
    
    def gradient(self, x, t):
        
        # 순전파
        self.loss(x, t)
        
        # 역전파
        dout = 1
        dout = self.lastLayer.backward(dout)
        
        layers = list(self.layers.values())
        layers.reverse()
        for layer in layers:
            dout = layer.backward(dout)
            
        # 결과 저장
        grads = {}
        grads['W1'] = self.layers['Affine1'].dW
        grads['b1'] = self.layers['Affine1'].db
        grads['W2'] = self.layers['Affine2'].dW
        grads['b2'] = self.layers['Affine2'].db
        
        return grads

In [41]:
### 5.7.3 오차역전파법으로 구한 기울기 검증하기

import sys, os
sys.path.append(os.pardir)
import numpy as np
from src.dataset.mnist import load_mnist
from src.ch05.two_layer_net import TwoLayerNet

# 데이터 읽기
(x_train, t_train), (x_test, t_test) = \
    load_mnist(normalize=True, one_hot_label=True)

network = TwoLayerNet(input_size=784, hidden_size=50, output_size=10)

x_batch = x_train[:3]
t_batch = t_train[:3]

grad_numerical = network.numerical_gradient(x_batch, t_batch)
grad_backprop = network.gradient(x_batch, t_batch)

# 각 가중치의 차이의 절댓값을 구한 후, 그 절댓값들의 평균을 낸다
for key in grad_numerical.keys():
    diff = np.average( np.abs(grad_backprop[key] - grad_numerical[key]) )
    print(key + ":" + str(diff))

W1:3.675225363121541e-10
b1:2.2597084914886823e-09
W2:4.82734310998579e-09
b2:1.395743221985213e-07


In [42]:
# 5.7.4 오차역전파법을 사용한 학습 구현하기

import sys, os
sys.path.append(os.pardir)
import numpy as np
from src.dataset.mnist import load_mnist
from src.ch05.two_layer_net import TwoLayerNet

# 데이터 읽기
(x_train, t_train), (x_test, t_test) = \
    load_mnist(normalize=True, one_hot_label=True)
network = TwoLayerNet(input_size=784, hidden_size=50, output_size=10)

iters_num = 10000
train_size = x_train.shape[0]
batch_size = 100
learning_rate = 0.1

train_loss_list = []
train_acc_list = []
test_acc_list = []

iter_per_epoch = max(train_size / batch_size, 1)

for i in range(iters_num):
    batch_mask = np.random.choice(train_size, batch_size)
    x_batch = x_train[batch_mask]
    t_batch = t_train[batch_mask]
    
    # 오차역전파법으로 기울기를 구한다
    grad = network.gradient(x_batch, t_batch)
    
    # 갱신
    for key in ('W1', 'b1', 'W2', 'b2'):
        network.params[key] -= learning_rate * grad[key]
        
    loss = network.loss(x_batch, t_batch)
    train_loss_list.append(loss)
    
    if i % iter_per_epoch == 0:
        train_acc = network.accuracy(x_train, t_train)
        test_acc = network.accuracy(x_test, t_test)
        train_acc_list.append(train_acc)
        test_acc_list.append(test_acc)
        print(train_acc, test_acc)

0.12438333333333333 0.121
0.9014666666666666 0.9043
0.9228166666666666 0.924
0.9357 0.9359
0.943 0.9428
0.9518166666666666 0.9499
0.9561 0.9536
0.9601666666666666 0.9574
0.9635833333333333 0.9606
0.9671 0.9615
0.9689 0.9644
0.9708833333333333 0.9648
0.9722833333333334 0.9649
0.9744833333333334 0.9679
0.9758166666666667 0.9674
0.9767166666666667 0.969
0.9785166666666667 0.9704
